apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- if .Values.secrets.hfToken }}
  HF_TOKEN: {{ .Values.secrets.hfToken | b64enc | quote }}
  {{- end }}
